# Generated by Django 3.2 on 2024-01-04 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2024, 'Нельзя добавлять произведения, которые еще не вышли.'), django.core.validators.MinValueValidator(1, 'Нельзя добавлять произведения, с годом меньше 1.')], verbose_name='Год выпуска'),
        ),
    ]
